[package]
name = "moonlander-trainer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = { version = "2.0.2", features = ["macos-shared-device"] }
rand = "0.8.5"
